// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isqpfwbnnhteolfnelne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzcXBmd2Jubmh0ZW9sZm5lbG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjkxNzIsImV4cCI6MjA3MzMwNTE3Mn0.2_OLHDbndqI2PWLpNkpeMvUkwvyiR7zqHfpSIlZ2-2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});